### ISSUE TITLE
xmacro xxx.xmacro : Error: [line 110]xmacro_block<inertia_box> is not defined

### ISSUE THREAD

**Issue by lienzzzz** [gezp/xmacro#2]
The test object is a project file
command:
`xmacro /test/sdf/model.sdf.xmacro
`
output:
Error: [line 110]xmacro_block<inertia_box> is not defined

**Comment by gezp** [comment]
`<inertia_box>` is pre-defined `xmacro block` in [common.sdf.xmacro](https://github.com/gezp/xmacro/blob/main/xmacro/common.sdf.xmacro) which is special for [sdformat](http://sdformat.org/) tool. you can run `xmacro4sdf /test/sdf/model.sdf.xmacro`, but this feature will be `deprecated`.

i don't want to add pre-defined `xmacro block` in this project so that it's a general xml macro tool.
